CREATE TABLE LANGUAGE(
    LANGUAGE_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL
);


CREATE TABLE TEACHER(
    ID NUMBER PRIMARY KEY,
    LANGUAGE_ID NUMBER NOT NULL,
    NAME VARCHAR2(100),
    SALARY NUMBER,
    CONSTRAINT LAN_TEACHER_FK FOREIGN KEY(LANGUAGE_ID) REFERENCES LANGUAGE(LANGUAGE_ID)
);