CREATE TABLE DOCTOR(
    DOCTOR_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100),
    SALARY NUMBER
);

CREATE TABLE PATIENT(
    PATIENT_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100),
    AGE NUMBER
);

CREATE TABLE DOCTOR_PATIENT(
    DOCTOR_ID NUMBER NOT NULL,
    PATIENT_ID NUMBER NOT NULL,
    CONSTRAINT pk_doctor_patient PRIMARY KEY (doctor_id, patient_id),
    CONSTRAINT fk_dp_doctor  FOREIGN KEY(DOCTOR_ID) REFERENCES DOCTOR(DOCTOR_ID),
    CONSTRAINT fk_dp_patient  FOREIGN KEY(PATIENT_ID) REFERENCES PATIENT(PATIENT_ID)
);