CREATE TABLE Player(
	ID NUMBER NOT NULL UNIQUE,
	NAME VARCHAR2(100) UNIQUE,
	AGE  NUMBER
);

CREATE TABLE MangerManger(
	ID NUMBER NOT NULL,
	NAME VARCHAR2(100) ,
	SALARY  NUMBER,
	CONSTRAINT id_name_composite UNIQUE(ID,NAME);
);


CREATE TABLE MangerManger(
	ID NUMBER PRIMARY KEY,
	NAME VARCHAR2(100) ,
	SALARY  NUMBER
);