CREATE TABLE EMPLOYEE(
    EMPLOYEE_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    AGE NUMBER
);

CREATE TABLE PHONE(
    PHONE_ID NUMBER PRIMARY KEY,
    PHONE_NUMBER CHAR(13) NOT NULL,
    EMPLOYEE_ID NUMBER NOT NULL UNIQUE ,
    CONSTRAINT EMP_PHONE_FK FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);