CREATE TABLE accounts (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,

    username VARCHAR2(20) NOT NULL,

    password VARCHAR2(255) NOT NULL,

    age NUMBER(3) NOT NULL,

    phone_number VARCHAR2(11) NOT NULL,

    balance NUMBER(15, 2) DEFAULT 0 NOT NULL,

    CONSTRAINT pk_accounts
        PRIMARY KEY (id),

    CONSTRAINT uq_accounts_phone
        UNIQUE (phone_number),

    CONSTRAINT ck_accounts_age
        CHECK (age >= 18),

    CONSTRAINT ck_accounts_balance
        CHECK (balance >= 0)
);


