SELECT TO_CHAR(sysdate,'DD-MON-YYYY') FROM dual;

SELECT TO_CHAR(sysdate,'Month YYYY') FROM dual;

SELECT SALARY,TO_CHAR(SALARY, 'FM99,999.99') AS FORMATTED_SALARY FROM EMPLOYEES;

SELECT SALARY,TO_CHAR(SALARY, 'FM$99,999.99') AS FORMATTED_SALARY FROM EMPLOYEES;