SELECT * FROM EMPLOYEES e ;

SELECT AVG(SALARY) FROM EMPLOYEES;

SELECT COUNT(EMPLOYEE_ID) FROM EMPLOYEES;

SELECT MAX(SALARY) FROM EMPLOYEES;

SELECT MIN(SALARY) FROM EMPLOYEES;

SELECT SUM(SALARY) FROM EMPLOYEES;

SELECT DEPARTMENT_ID ,AVG(SALARY)  FROM EMPLOYEES GROUP BY DEPARTMENT_ID;

SELECT JOB_ID,COUNT(EMPLOYEE_ID)  FROM EMPLOYEES GROUP BY JOB_ID;

SELECT DEPARTMENT_ID ,SUM(SALARY) AS total_salary  FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING SUM(SALARY) >50000;

SELECT AVG(COMMISSION_PCT),AVG(NVL(COMMISSION_PCT,0)) FROM EMPLOYEES;

SELECT COUNT(EMPLOYEE_ID) FROM EMPLOYEES WHERE SALARY >10000;

SELECT JOB_ID ,MAX(SALARY),MIN(SALARY) FROM EMPLOYEES GROUP BY JOB_ID;

SELECT manager_id,SUM(salary) FROM employees GROUP BY manager_id;

SELECT JOB_ID,DEPARTMENT_ID,SUM(SALARY) FROM employees GROUP BY JOB_ID,DEPARTMENT_ID;

SELECT JOB_ID,COUNT(EMPLOYEE_ID)  FROM EMPLOYEES GROUP BY JOB_ID HAVING COUNT(EMPLOYEE_ID) > 5;

SELECT department_id,
    COUNT(employee_id) AS total_employees,
    AVG(salary) AS average_salary,
    MAX(salary) AS maximum_salary,
    MIN(salary) AS minimum_salary
FROM employees
GROUP BY department_id;


SELECT department_id FROM EMPLOYEES GROUP BY department_id  HAVING AVG(SALARY) > 8000 AND COUNT(EMPLOYEE_ID) < 10;

SELECT 
    department_id,
    SUM(salary) AS total_salary
FROM employees
GROUP BY department_id
HAVING SUM(salary) = (
    SELECT MAX(SUM(salary))
    FROM employees
    GROUP BY department_id
);

SELECT 
    department_id,
    SUM(salary) AS total_salary
FROM employees
GROUP BY department_id
ORDER BY total_salary DESC
FETCH FIRST 1 ROW ONLY;


SELECT 
    department_id,
    SUM(salary) AS Total_Salary,
    AVG(salary) AS Average_Salary
FROM employees
GROUP BY department_id;
