CREATE TABLE EMP_TEST(
	NAME VARCHAR2(100)	
);

INSERT INTO EMP_TEST VALUES('   bakr omar   ');

SELECT  TRIM(NAME) TRM FROM EMP_TEST;

SELECT LTRIM(NAME) TRM FROM EMP_TEST;

SELECT RTRIM(NAME) TRM FROM EMP_TEST;

INSERT INTO EMP_TEST VALUES('#ahme omar*');

SELECT LTRIM(NAME,'#') TRM FROM EMP_TEST;

SELECT RTRIM(NAME,'*') TRM FROM EMP_TEST;

SELECT RTRIM(LTRIM(NAME,'#'),'*') TRM FROM EMP_TEST;