SELECT * FROM EMPLOYEES;

SELECT FIRST_NAME,REPLACE(FIRST_NAME,'a','@') FROM EMPLOYEES;

SELECT REPLACE('This is the old data','old','new') RPL FROM dual;

CREATE TABLE PRODUCT(
	PRODUCT_NAME VARCHAR2(100)	
);

INSERT INTO PRODUCT VALUES('LAPTOP');
INSERT INTO PRODUCT VALUES('Mobile Phone');
INSERT INTO PRODUCT VALUES('PC Computer');

SELECT PRODUCT_NAME,LPAD(PRODUCT_NAME,15,'*') FROM PRODUCT;

SELECT PRODUCT_NAME,RPAD(PRODUCT_NAME,15,'#') FROM PRODUCT;