CREATE TABLE STUDENTS1(
	NAME VARCHAR2(100),
	MARKS NUMBER
);


INSERT INTO STUDENTS1(NAME,MARKS) VALUES('AHMED',99);
INSERT INTO STUDENTS1(NAME,MARKS) VALUES('BAKR',88);
INSERT INTO STUDENTS1(NAME,MARKS) VALUES('OMAR',76);
INSERT INTO STUDENTS1(NAME,MARKS) VALUES('MOHAMED',60);
INSERT INTO STUDENTS1(NAME,MARKS) VALUES('IBRAHIM',65);

SELECT * FROM STUDENTS1;

SELECT NAME,MARKS ,CASE
        	WHEN MARKS >= 90 THEN 'A'
        	WHEN MARKS >= 80 THEN 'B'
        	WHEN MARKS >= 70 THEN 'C'
        	ELSE 'F'
        END AS "GRADE"
		FROM STUDENTS1;