CREATE TABLE accounts (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(20 CHAR) NOT NULL,
    password VARCHAR2(255 CHAR) NOT NULL,
    age NUMBER(3) NOT NULL,
    phone_number VARCHAR2(11 CHAR) NOT NULL,
    balance NUMBER(15, 2) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_accounts_username UNIQUE (username),
    CONSTRAINT uq_accounts_phone UNIQUE (phone_number),
    CONSTRAINT ck_accounts_age CHECK (age >= 18),
    CONSTRAINT ck_accounts_balance CHECK (balance >= 0)
);

-- Makes username uniqueness case-insensitive: User1 and user1 cannot both exist.
CREATE UNIQUE INDEX uq_accounts_username_upper ON accounts (UPPER(username));
