SELECT * FROM  HR.EMPLOYEES WHERE employee_id BETWEEN 100 AND 105;

SELECT * FROM  HR.EMPLOYEES WHERE employee_id IN (151 , 152, 153, 154 , 155);

SELECT * FROM  HR.EMPLOYEES WHERE  FIRST_NAME LIKE 'P%' OR FIRST_NAME LIKE 'p%';

SELECT * FROM HR.EMPLOYEES WHERE FIRST_NAME LIKE '%A' OR FIRST_NAME LIKE '%a';

SELECT * FROM HR.EMPLOYEES WHERE FIRST_NAME LIKE '%A%' OR FIRST_NAME LIKE '%a%';

SELECT * FROM HR.EMPLOYEES WHERE FIRST_NAME LIKE 'E%' OR FIRST_NAME LIKE 'e%' ;

SELECT * FROM HR.EMPLOYEES WHERE MANAGER_ID IS NULL;

SELECT * FROM HR.EMPLOYEES WHERE MANAGER_ID IS NOT NULL;

INSERT INTO HR.EMPLOYEES 
(employee_id,first_name,last_name,email,phone_number,hire_date,job_id,salary,commission_pct,manager_id,department_id)
VALUES 
(207,'Ahmed','Omar','Test@gmail.com','0123456789',TRUNC(SYSDATE),'PR_REP',50000, NULL,NULL,110);

SELECT * FROM HR.EMPLOYEES WHERE JOB_ID IN ('AD_VP', 'IT_PROG');

 SELECT * FROM HR.EMPLOYEES ORDER BY LAST_NAME ASC;

SELECT * FROM HR.EMPLOYEES ORDER BY HIRE_DATE DESC;

SELECT * FROM HR.EMPLOYEES ORDER BY DEPARTMENT_ID ASC, SALARY DESC;

SELECT LOWER(LAST_NAME) AS last_name_lowercase, employees.* FROM HR.employees;

SELECT UPPER (FIRST_NAME) AS first_name_uppercase, employees.* FROM HR.employees;

SELECT INITCAP (FIRST_NAME) AS first_name ,INITCAP (LAST_NAME) AS last_name FROM HR.employees;

SELECT * FROM HR.EMPLOYEES WHERE LOWER(LAST_NAME)='smith';