DROP TABLE item;

CREATE TABLE item (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL UNIQUE,
    price NUMBER(10,2) NOT NULL,
    total_number NUMBER NOT NULL,
    CONSTRAINT check_price CHECK(price >= 0),
    CONSTRAINT check_totalNumber CHECK(total_number >= 0),
    CONSTRAINT check_item_name_length CHECK(LENGTH(TRIM(name)) BETWEEN 2 AND 100)
);

CREATE TABLE item_details (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    item_id NUMBER NOT NULL,
    description VARCHAR2(500),
    category VARCHAR2(100),
    manufacturer VARCHAR2(100),
    warranty_months NUMBER,

    CONSTRAINT item_details_pk
        PRIMARY KEY (id),

    CONSTRAINT item_details_item_fk
        FOREIGN KEY (item_id)
        REFERENCES item(id)
        ON DELETE CASCADE,

    CONSTRAINT item_details_item_unique
        UNIQUE (item_id),

    CONSTRAINT item_details_warranty_check
        CHECK (warranty_months >= 0)
);



SELECT * FROM item;	

UPDATE item_details set

INSERT INTO item (name, price, total_number) VALUES ('Laptop', 15000, 10);
INSERT INTO item (name, price, total_number) VALUES ('Smartphone', 8000, 25);
INSERT INTO item (name, price, total_number) VALUES ('Headphones', 500, 50);
INSERT INTO item (name, price, total_number) VALUES ('Keyboard', 300, 40);
INSERT INTO item (name, price, total_number) VALUES ('Mouse', 150, 60);
INSERT INTO item (name, price, total_number) VALUES ('Monitor', 2500, 15);
INSERT INTO item (name, price, total_number) VALUES ('Printer', 2000, 8);
INSERT INTO item (name, price, total_number) VALUES ('Tablet', 6000, 12);
INSERT INTO item (name, price, total_number) VALUES ('USB Flash Drive', 100, 100);
INSERT INTO item (name, price, total_number) VALUES ('External Hard Drive', 1200, 20);

INSERT INTO item_details (item_id,description,category,manufacturer,warranty_months)
VALUES ((SELECT id FROM item WHERE name='Laptop'),'High performance laptop suitable for work and study.','Electronics','Dell',24);

INSERT INTO item_details (item_id,description,category,manufacturer,warranty_months)
VALUES ((SELECT id FROM item WHERE name='Smartphone'),'Modern smartphone with good camera and battery life.','Electronics','Samsung',12);

INSERT INTO item_details (item_id,description,category,manufacturer,warranty_months)
VALUES ((SELECT id FROM item WHERE name='Headphones'),'Comfortable wired headphones with clear sound.','Accessories','Sony',6);

INSERT INTO item_details (item_id,description,category,manufacturer,warranty_months)
VALUES ((SELECT id FROM item WHERE name='Keyboard'),'Standard keyboard suitable for office use.','Accessories','Logitech',12);

INSERT INTO item_details (item_id,description,category,manufacturer,warranty_months)
VALUES ((SELECT id FROM item WHERE name='Mouse'),'Optical mouse with smooth movement and simple design.','Accessories','HP',6);

INSERT INTO item_details (item_id,description,category,manufacturer,warranty_months)
VALUES ((SELECT id FROM item WHERE name='Monitor'),'Full HD monitor suitable for office and gaming use.','Electronics','LG',24);

INSERT INTO item_details (item_id,description,category,manufacturer,warranty_months)
VALUES ((SELECT id FROM item WHERE name='Printer'),'Office printer suitable for documents and reports.','Office Equipment','Canon',12);

INSERT INTO item_details (item_id,description,category,manufacturer,warranty_months)
VALUES ((SELECT id FROM item WHERE name='Tablet'),'Portable tablet suitable for reading, study, and browsing.','Electronics','Lenovo',12);

INSERT INTO item_details (item_id,description,category,manufacturer,warranty_months)
VALUES ((SELECT id FROM item WHERE name='USB Flash Drive'),'Small USB storage device for files and backups.','Storage','Kingston',3);

INSERT INTO item_details (item_id,description,category,manufacturer,warranty_months)
VALUES ((SELECT id FROM item WHERE name='External Hard Drive'),'External storage drive suitable for large backups.','Storage','Western Digital',24);

SELECT * FROM item_details;

DELETE FROM item WHERE id=1;

DROP TABLE account;


SELECT * FROM account;

CREATE TABLE account (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USERNAME VARCHAR2(100) NOT NULL UNIQUE,
    EMAIL VARCHAR2(150) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO account (USERNAME, EMAIL, PASSWORD)
VALUES ('ahmed', 'ahmed@test.com', 'ahmed123');



SELECT table_name
FROM user_tables
WHERE table_name = 'ACCOUNT';

SELECT * FROM account;
